#tomcat
server.port: 8081

security:
  config:
    prefix: Bearer
    key: SECRET_KEY
    expiration: 3600000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:projeto
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect