insert into cargo (id_cargo, cargo, descricao) values (1,'DIRETORGERAL','ROLE_ADMIN');
insert into cargo (id_cargo, cargo, descricao) values (2,'DIRETOR','ROLE_GERENTES ROLE_ADMIN');
insert into cargo (id_cargo, cargo, descricao) values (3,'GERENTE','ROLE_DIRETORES ROLE_GERENTES ROLE_ADMIN');
insert into cargo (id_cargo, cargo, descricao) values (4,'VENDEDOR','ROLE_ADMIN ROLE_DIRETORES ROLE_GERENTES ROLE_VENDEDORES');

insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (1,'Edson A. do Nascimento','pele','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','pele@magazineaziul.com.br',1);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (2,'Vagner Mancini','vagner.mancini','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','vagner.mancini@magazineaziul.com.br',2);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (3,'Abel Ferreira','abel.ferreira','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','abel.ferreira@magazineaziul.com.br',2);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (4,'Rogerio Ceni','rogerio.ceni','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','rogerio.ceni@magazineaziul.com.br',2);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (5,'Ronaldinho Gaucho','ronaldinho.gaucho','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','ronaldinho.gaucho@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (6,'Roberto Firmino','roberto.firmino','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','roberto.firmino@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (7,'Alex de Souza','alex.de.souza','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','alex.de.souza@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (8,'Françoaldo Souza','françoaldo.souza','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','françoaldo.souza@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (9,'Romário Faria','romário.faria','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','romário.faria@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (10,'Ricardo Goulart','ricardo.goulart','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','ricardo.goulart@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (11,'Dejan Petkovic','dejan.petkovic','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','dejan.petkovic@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (12,'Deyverson Acosta','deyverson.acosta','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','deyverson.acosta@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (13,'Harlei Silva','harlei.silva','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','harlei.silva@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (14,'Walter Henrique','walter.henrique','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','walter.henrique@magazineaziul.com.br',3);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (15,'Afonso Afancar','afonso.afancar','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','afonso.afancar@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (16,'Alceu Andreoli','alceu.andreoli','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','alceu.andreoli@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (17,'Amalia Zago','amalia.zago','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','amalia.zago@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (18,'Carlos Eduardo','carlos.eduardo','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','carlos.eduardo@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (19,'Luiz Felipe','luiz.felipe','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','luiz.felipe@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (20,'Breno','breno','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','breno@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (21,'Emanuel','emanuel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','emanuel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (22,'Ryan','ryan','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','ryan@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (23,'Vitor Hugo','vitor.hugo','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','vitor.hugo@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (24,'Yuri','yuri','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','yuri@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (25,'Benjamin','benjamin','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','benjamin@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (26,'Erick','erick','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','erick@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (27,'Enzo Gabriel','enzo.gabriel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','enzo.gabriel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (28,'Fernando','fernando','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','fernando@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (29,'Joaquim','joaquim','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','joaquim@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (30,'André','andré','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','andré@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (31,'Raul','raul','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','raul@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (32,'Marcelo','marcelo','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','marcelo@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (33,'Julio César','julio.césar','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','julio.césar@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (34,'Cauê','cauê','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','cauê@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (35,'Benício','benício','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','benício@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (36,'Vitor Gabriel','vitor.gabriel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','vitor.gabriel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (37,'Augusto','augusto','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','augusto@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (38,'Pedro Lucas','pedro.lucas','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','pedro.lucas@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (39,'Luiz Gustavo','luiz.gustavo','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','luiz.gustavo@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (40,'Giovanni','giovanni','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','giovanni@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (41,'Renato','renato','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','renato@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (42,'Diego','diego','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','diego@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (43,'João Paulo','joão.paulo','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','joão.paulo@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (44,'Renan','renan','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','renan@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (45,'Luiz Fernando','luiz.fernando','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','luiz.fernando@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (46,'Anthony','anthony','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','anthony@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (47,'Lucas Gabriel','lucas.gabriel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','lucas.gabriel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (48,'Thales','thales','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','thales@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (49,'Luiz Miguel','luiz.miguel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','luiz.miguel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (50,'Henry','henry','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','henry@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (51,'Marcos Vinicius','marcos.vinicius','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','marcos.vinicius@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (52,'Kevin','kevin','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','kevin@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (53,'Levi','levi','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','levi@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (54,'Enrico','enrico','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','enrico@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (55,'João Lucas','joão.lucas','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','joão.lucas@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (56,'Hugo','hugo','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','hugo@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (57,'Luiz Guilherme','luiz.guilherme','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','luiz.guilherme@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (58,'Matheus Henrique','matheus.henrique','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','matheus.henrique@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (59,'Miguel','miguel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','miguel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (60,'Davi','davi','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','davi@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (61,'Gabriel','gabriel','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','gabriel@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (62,'Arthur','arthur','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','arthur@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (63,'Lucas','lucas','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','lucas@magazineaziul.com.br',4);
insert into usuario (id_usuario, nome, login, senha, email, id_cargo) values (64,'Matheus','matheus','$2y$10$K5ueK8ItEI1MsRZGIzO9AOy1iJmLPPXH6mvOBYc997iPkkEihYNHa','matheus@magazineaziul.com.br',4);

